### PR TITLE
[WIP] Prototype for top-level DSL and supporting `benchmark-driver mybench.rb`

### PR DESCRIPTION
**Pull request by eregon**
A prototype for the top-level DSL as mentioned in https://github.com/benchmark-driver/benchmark-driver/issues/67#issuecomment-615980651

This makes all variants of `app_fib` in https://github.com/eregon/ruby/commit/964ab520ef092cae69d2891b019e8fa0e4813936 work with
`benchmark-driver file.rb/yml`:
```
$ benchmark-driver benchmark/app_fib2.rb
Warming up --------------------------------------
             app_fib      4.038 i/s -       5.000 times in 1.238384s (247.68ms/i)
Calculating -------------------------------------
             app_fib      4.027 i/s -      12.000 times in 2.979929s (248.33ms/i)

$ benchmark-driver benchmark/app_fib3.rb
Warming up --------------------------------------
             app_fib      3.979 i/s -       4.000 times in 1.005206s (251.30ms/i)
Calculating -------------------------------------
             app_fib      4.043 i/s -      11.000 times in 2.720868s (247.35ms/i)

$ benchmark-driver benchmark/app_fib.yml 
Warming up --------------------------------------
             app_fib      4.010 i/s -       5.000 times in 1.246770s (249.35ms/i)
Calculating -------------------------------------
             app_fib      4.025 i/s -      12.000 times in 2.981339s (248.44ms/i)


```
The original [benchmark/app_fib.rb](https://github.com/eregon/ruby/blob/top-level-dsl/benchmark/app_fib.rb) has no warmup as before (behavior unchanged):
```
$ benchmark-driver benchmark/app_fib.rb 
Calculating -------------------------------------
             app_fib      4.014 i/s -       1.000 times in 0.249122s (249.12ms/i)
```

@k0kubun What do you think, is that close to what you had in mind for the top-level DSL?

### CODE REVIEW

**Comment by eregon** [comment]
Another idea for a top-level DSL would be to have something like:
```ruby
def fib n
  if n < 3
    1
  else
    fib(n-1) + fib(n-2)
  end
end

benchmark 'app_fib' do
  fib(34)
end
```

Which would be actually parsed and transformed into:
```ruby
prelude <<RUBY
def fib n
  if n < 3
    1
  else
    fib(n-1) + fib(n-2)
  end
end
RUBY

report 'app_fib', <<RUBY
fib(34)
RUBY
```
(or directly into a config object and generated measurement code, of course)

That would still allow using pure Ruby syntax in the `.rb` file, without having the code in Strings, which means it'd still look like regular Ruby code and the interface would be extremely simple.
It seems GitHub no longer highlights code in `<<RUBY` or `<<~RUBY` :disappointed: , even though it used to in https://github.com/rubygems/bundler/pull/6599/files#r197651127

However the fact we'd remove the block, and add whatever code between `benchmark{}` as prelude, and execute that code in a delayed way might be confusing.

**Comment by eregon** [comment]
I prototyped that second idea for `benchmark {}` in https://github.com/benchmark-driver/benchmark-driver/commit/4b945bfe22807010a868d945e993fa9862faccee

**Comment by k0kubun** [comment]
> What do you think, is that close to what you had in mind for the top-level DSL?

Yeah, while I also wondered if we could do it better to require less typing than `RUBY>>` and `RUBY`, like your second idea.

> It seems GitHub no longer highlights code in <<RUBY or <<~RUBY

Hmm, not sure why it didn't work for you, but strangely it works in my comment:

```ruby
prelude <<RUBY
def fib n
  if n < 3
    1
  else
    fib(n-1) + fib(n-2)
  end
end
RUBY

report 'app_fib', <<RUBY
fib(34)
RUBY
```

It seems it doesn't need to be `RUBY` in GitHub's syntax highlight by the way.

> Another idea for a top-level DSL
>
> I prototyped that second idea for `benchmark {}` in https://github.com/benchmark-driver/benchmark-driver/commit/4b945bfe22807010a868d945e993fa9862faccee

Thanks for prototyping it. This looks becautiful.

However, I find some trade-offs here, compared to the YAML format:

* pros:
  * Nice editor supports like syntax highlight and completion when writing benchmark targets.
  * No weird feeling to write Ruby in a YAML file
  * Experience to write a benchmark script is closer to other benchmark tools
* cons:
  * Too magical. Probably it becomes harder to understand what's going on behind it.
  * Hence people may try to use `if` or loops around `benchmark`, while it doesn't work.
     * For example people may try `if RUBY_VERSION >= "2.5.0"` when rewriting https://github.com/benchmark-driver/ruby-method-benchmarks/blob/master/benchmarks/String/capitalize.yml.
     * So I think we should not "parse" a Ruby script on our own but eval them to get prelude / benchmark. If it's not actually working like Ruby but YAML, I think just using YAML is better to avoid confusion and to keep it easy to maintain.
  * Where do we put attributes like per-benchmark `prelude` and `loop_version` like https://github.com/k0kubun/ruby/blob/master/benchmark/cgi_escape_html.yml.

<hr>

So, I'd like to take your first idea, with some minor tweaks:

* Warn and eventually deprecate the mode currently used by `app_fib.rb` (you need to check if ko1 is happy about replacing the legacy mode with the new top-level DSL)
* Alias `report` to `benchmark` (and probably even not supporting `report` in the top-level mode) to make it closer to YAML and what you wanted to write in the second idea

Some variations we could write are:

```ruby
# what you wrote, and what some editors support
prelude <<RUBY
def fib n
  if n < 3
    1
  else
    fib(n-1) + fib(n-2)
  end
end
RUBY

benchmark <<RUBY
fib(34)
RUBY
```

```ruby
# nobu's style
prelude "#{<<~"begin;"}\n#{<<~"end;"}"
begin;
  def fib n
    if n < 3
      1
    else
      fib(n-1) + fib(n-2)
    end
  end
end;

benchmark "#{<<~"begin;"}\n#{<<~"end;"}"
begin;
  fib(34)
end;
```

```ruby
# ko1's style (I like and use this one)
prelude %{
  def fib n
    if n < 3
      1
    else
      fib(n-1) + fib(n-2)
    end
  end
}

benchmark %{ fib(31) }
```

Lastly, I have some opinions about this implementation, like... I don't think we need to extend `main`, and also the DSL implementation should be shared between `Benchmark.driver` and top-level DSL. If you support the above interface, I'll implement it by myself for you.

**Comment by eregon** [comment]
> Hmm, not sure why it didn't work for you, but strangely it works in my comment:

It seems to only work when doing a `Preview`.
I would think this is probably a GitHub bug, I'll report it.

Here is what I see when reading your comment:
Screenshot from 2020-05-03 13-59-25
And here is what it looks like when doing a preview of quoting your comment:
Screenshot from 2020-05-03 13-59-38

**Comment by eregon** [comment]
Thanks for the review!

> Thanks for prototyping it. This looks becautiful.

:smiley: 

>   * Hence people may try to use `if` or loops around `benchmark`, while it doesn't work.
>     
>     * For example people may try `if RUBY_VERSION >= "2.5.0"` when rewriting https://github.com/benchmark-driver/ruby-method-benchmarks/blob/master/benchmarks/String/capitalize.yml.
>     * So I think we should not "parse" a Ruby script on our own but eval them to get prelude / benchmark.

Yes, this is indeed an issue.
We could check that `benchmark` is at the start of the line (no indentation) and error if it isn't, but that doesn't really prevent adding a `if` or loop/block around (just mis-indented).

One wild idea would be to eval the Ruby script, and use the `benchmark` block's `source_location` to get the benchmark code as a String, but then it seems challenging to get the prelude String, e.g. if `benchmark` is nested in a while loop/each block or so, as we'd need to remove the `while`/`each` but keep the partial setup (e.g., variables declared in that loop) until then. Basically it seems impossible to support any kind of loop around the `benchmark` call, but maybe that's not needed and an error in such a case would be OK.

So I agree, it's probably too confusing and would not be easy to verify when it's OK to treat it like that.

To support `benchmark {}` we'd probably want each measured Ruby to execute the file, and accept the block call overhead (which becomes quite similar to `benchmark-ips` then, but `benchmark-ips` doesn't support running and comparing multiple Rubies in one command).

Another idea: we could potentially get the caller binding (or pass it like `benchmark binding do`), and then `caller_binding.eval "timing code; while ...; #{benchmark_code}; end; timing code;"` so there isn't a block overhead but it's a bit hacky.

>   * Where do we put attributes like per-benchmark `prelude` and `loop_version` like https://github.com/k0kubun/ruby/blob/master/benchmark/cgi_escape_html.yml.

This one also applies to the first solution, how should we do per-benchmark prelude in the top-level DSL?
Maybe each `prelude STRING` applies to the next benchmark, and the Ruby code can compose them if there is a common part?
Having `setup` (= per-benchmark prelude) and `prelude` (= shared prelude for all benchmarks) is another way.
We could also try to have some grouping per benchmark with blocks or so but then the DSL becomes more complicated.

> * Warn and eventually deprecate the mode currently used by `app_fib.rb` (you need to check if ko1 is happy about replacing the legacy mode with the new top-level DSL)
> * Alias `report` to `benchmark` (and probably even not supporting `report` in the top-level mode) to make it closer to YAML and what you wanted to write in the second idea

:+1: 

> Some variations we could write are:

Interesting, the last one `%{}`-style is the most succinct but e.g., doesn't highlight correctly on GitHub and I guess in no editor.
So I think the first style is the one we should recommend in the README.
If the expression is short, e.g., `fib(34)` then of course just  `"fib(34)"` or `%{ fib(34) }` work too (no syntax highlighting but probably doesn't matter for such trivial code).

Note that with `<<RUBY` in RubyMine, basic syntax highlighting works but that's all, it's not as good as having the code there, and e.g., `Go to definition` doesn't work. The `benchmark {}` solves that.

`<<RUBY` syntax highlights in VSCode and some versions of Atom. In latest Atom it seems to not work, but maybe some setting fixes it or it's a regression. It doesn't work in Vim and Emacs.
But maybe we can make this style more popular and more editors support it.

> Lastly, I have some opinions about this implementation, like... I don't think we need to extend `main`

Would you rather `instance_eval` then? I thought it's less disruptive to add a couple methods to `main` than changing top-level `self`.

**Comment by eregon** [comment]
BTW, what's the purpose of `loop_count` e.g. in https://github.com/k0kubun/ruby/blob/master/benchmark/cgi_escape_html.yml?
Doesn't the IPS runner remove the need for that?

**Comment by eregon** [comment]
> Another idea: we could potentially get the caller binding [...]

Actually we can just use `Proc#binding`. I played a bit with that in https://gist.github.com/eregon/eb2892005799c0cf82ced16e2e065b5c#file-fib-rb and it works for a loop around `benchmark`.
It means loading the Ruby script in every subprocess, but still being able to remove the block and add code as wanted around.

I'm curious what you think of that approach. Obviously it's very much a prototype, but it seems less hacky than I thought initially (could use `eval rescue SyntaxError` to figure out the block end).

**Comment by k0kubun** [comment]
> It seems to only work when doing a Preview.

lol, yeah it seemed like so to me too. It also seemed to work just after posting it (and maybe after reloading too), but it doesn't work today anymore.

> So I think the first style is the one we should recommend in the README.

Nah, as commented above, I "like" the `%{ }` syntax. The `RUBY>>` doesn't work for Vim and GitHub, and also `%{ }` is succinct as you said. The only beneficiary is RubyMine users. If this mode generates this kind of Rubocop-ish discussion, well, probably the current no-DSL Ruby mode would be better.

> Would you rather instance_eval then? I thought it's less disruptive to add a couple methods to main than changing top-level self.

No need to change top-level self or main. We can just create a random (not top-level) instance which has methods for DSL, and instane_eval DSL code with it.

> This one also applies to the first solution, how should we do per-benchmark prelude in the top-level DSL?

Good question. We'd need to add some keyword arguments in `report` (or its alias `benchmark`) and it could be like:

```rb
benchmark 'escape_html_long_none',
  prelude: %{ str = "abcde" * 300 },
  script:  %{ CGI.escapeHTML(str) },
  loop_count: 1000000
```

But at the same time, why not just use YAML for describing this kind of information? At least I don't want to write `RUBY>>` and `RUBY` 7 times in the same file, so syntax highlight wouldn't work for RubyMine either.

If the problem is all about editor support, I think what we need to fix is editors or their plugin, not the tool interpreting the code written by that. I don't want to workaround editor's problem by spending time to discussing and maintaining magical DSL.

> BTW, what's the purpose of loop_count e.g. in https://github.com/k0kubun/ruby/blob/master/benchmark/cgi_escape_html.yml?
Doesn't the IPS runner remove the need for that?

It's a trade-off between warmup time to calculate loop_count vs maintaining loop_count. When I want to run the same benchmark script many times, I tend to write `loop_count` to obviate warmup for quick development.

> > Another idea: we could potentially get the caller binding [...]
>
> Actually we can just use Proc#binding. I played a bit with that in https://gist.github.com/eregon/eb2892005799c0cf82ced16e2e065b5c#file-fib-rb and it works for a loop around benchmark.
It means loading the Ruby script in every subprocess, but still being able to remove the block and add code as wanted around.
>
> I'm curious what you think of that approach. Obviously it's very much a prototype, but it seems less hacky than I thought initially (could use eval rescue SyntaxError to figure out the block end).

Hats off to you, it's an interesting idea and I couldn't think of it.

My take for this one is:

* pros:
  * It seems `Binding#eval` probably doesn't add too much extra overhead when referring to local variables in binding.
* cons:
  * It's still parsing a Ruby script, just for knowing information which YAML could easily give. What if a block is created from a source built dynamically? I think maintenance cost to make it seem like a real block outweighs the benefit for editors.
  * A process parsing `benchmark` and one running `prelude` / `benchmark` are the same. It consumes extra memory in a target process and it's not desirable for runner like `memory`.

<hr>

As I think benchmark-driver should be maintainable with trivial effort, I'm not going to accept any interface requiring to parse a Ruby script using `source_location`, when it can be solved easily by just using YAML. I'd like to focus on MJIT development instead of discussing magical DSL and implementation which could be just `YAML.load`.

So, what I _may_ accept here seems only the top-level DSL that could be used like `prelude %{ ... }` and `benchmark %{ ... }`. But before considering that, could you first clarify:

* What's the most important problem you want to fix here?
* Do you think we can just use YAML to solve the problem if we can let GitHub and RubyMine recognize YAML files as Ruby-embedded YAML?

**Comment by eregon** [comment]
> If the problem is all about editor support, I think what we need to fix is editors or their plugin, not the tool interpreting the code written by that. I don't want to workaround editor's problem by spending time to discussing and maintaining magical DSL.

It seems hard to fix editor support (would take a long time, need to discuss, too many editors, etc).
It seems the only reliable and portable way to have syntax highlighting and IDE integration is to use plain Ruby code, not in Strings, and then find a way to extract that code for benchmark-driver (e.g., as my 2 experiments do).

> It's a trade-off between warmup time to calculate loop_count vs maintaining loop_count. When I want to run the same benchmark script many times, I tend to write loop_count to obviate warmup for quick development.

A hardcoded count can quickly become a problem if run on another Ruby implementation, or the JIT gets a lot faster, because then the benchmark might run for a very short time, which makes it harder to measure variance, and makes it less stable, and have less time to warmup/JIT.
I would recommend to never use `loop_count` (at least not in CRuby benchmarks), and rather make sure the warmup run by benchmark-driver is fast enough.
For development, it seems OK to be able to override `loop_count` on the command line as an option, but I would not set the `loop_count` for any measurement over a longer time or with different Rubies.

> So, what I _may_ accept here seems only the top-level DSL that could be used like `prelude %{ ... }` and `benchmark %{ ... }`. But before considering that, could you first clarify:
> 
> * What's the most important problem you want to fix here?

Good point. I wanted to experiment with better ways to specify the benchmark.
As said above, the only way to get syntax highlighting and IDE integration is for the benchmark to be Ruby code, not code in Strings (at least from the point of view of the editor).
I think something based on my 2 experiments to make `warmup; benchmark { ... }` work would be nice, maybe initially as a plugin or "experimental".
That mode cannot easily support different preludes or so, I think it doesn't matter much, there are good cases for YAML and there are good cases for this mode. Also, in a Ruby script people seem to be OK to use a single `prelude` for all benchmarks, i.e., setup everything then the code for each benchmark. For the [cgi_escape_html example](https://github.com/k0kubun/ruby/blob/master/benchmark/cgi_escape_html.yml) I'd just different names for the various strings instead of all using `str`.

Currently the only mode that accepts plain Ruby code is `benchmark-driver script.rb`.
But that mode has a major problem:
It cannot repeat the benchmark, only a single timed run, which includes time to define all classes, methods, constants, etc in the benchmark, which means no way to get a good error estimation or to do warmup (inside the process). This is because there is no hint of what part is the `prelude` and what part is the `benchmark`, and running the prelude multiple times would be problematic (e.g., it would redefine methods, which would throw away JIT'ed code, and can be slow, etc).
It's better than `time ruby bench.rb` (nice) but only because it avoids VM startup + parsing the main script.

So I identified 3 things I'd really want for benchmark-driver:
* A way to specify the benchmark with Ruby code in a Ruby file to get proper IDE/editor support, and a way to separate prelude and benchmarks to be able to do warmup. I think that mode can be more restricted than YAML, and I don't think that's an issue, it's something that comes naturally out of using an actual `.rb` file with Ruby code.
* Actually do warmup (for JIT, etc) (#68)
* Support `benchmark-driver file-using-Benchmark.driver-DSL.rb` so there is no need to e.g. specify `rbenv` inside the benchmark file which seems inconvenient. Also that way all modes can be run with `benchmark-driver file.rb`, and any command-line option can be used for the DSL mode too. The DSL mode gives the possibility to have some basic syntax highlighting with `<<RUBY` and IMHO I think should be as powerful as the YAML mode. With that I think we should document better the modes in the README.

> * Do you think we can just use YAML to solve the problem if we can let GitHub and RubyMine recognize YAML files for `benchmark-driver` as Ruby-embedded YAML by a YAML comment?

It would help, but it would likely only solve the issue for these 2 "editors". So it doesn't seem a practical solution unfortunately. It would still be helpful for benchmarks using YAML files though.

**Comment by eregon** [comment]
I'll close this PR because I think the top-level DSL doesn't really improve things:
* Syntax highlighting works only if using `<<RUBY` and RubyMine and basically nowhere else (and even then, no IDE support/go to definition).
* The existing DSL mode doesn't seem much harder to use, and can also have syntax highlighting with `<<RUBY`.
* It cannot replace YAML 1-1 easily, and Ruby code tends to be structured differently than YAML anyway (e.g., for multiples preludes).

**Pull request closed without merging**
